SELECT P.PRODUCT_CODE, sum(OS.SALES_AMOUNT * P.PRICE) as SALES
from OFFLINE_SALE OS left join PRODUCT P on (OS.PRODUCT_ID = P.PRODUCT_ID)
group by P.PRODUCT_ID
order by SALES desc, P.PRODUCT_CODE
