select I.ITEM_ID, I.ITEM_NAME, I.RARITY
from ITEM_INFO I join ITEM_TREE T on (I.ITEM_ID = T.ITEM_ID)
where T.PARENT_ITEM_ID IN (SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE')
order by T.ITEM_ID desc
